title = "YXL's Blog"

baseurl = "/"

copyright = "Copyright © 2019-2019 yxl.netlify.com All Rights Reserved!"

googleAnalytics = "UA-136782661-1"

disqusShortname = "yxl76-zh"

############################
## Advanced options below ##
############################

theme = "academic"

enableGitInfo = false

defaultContentLanguage = "en"
hasCJKLanguage = true
defaultContentLanguageInSubdir = true

paginate = 10
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

[blackfriday]
  hrefTargetBlank = true
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

[Permalinks]
  post = "/blog/:slug/"