[en]
  languageCode = "en-us"

[zh]
  languageCode = "zh-Hans"
  contentDir = "zh_content"
  title = "YXL的小屋"
  [zh.params]
    description = ""

[[zh.menu.main]]
  name = "关于"
  url = ""
  weight = 15

[[zh.menu.main]]	
  name = "文章"
  url = "/post"
  weight = 25

[[zh.menu.main]]
  name = "类别"
  url = "/categories"
  weight = 55

[[zh.menu.main]]
  name = "标签"
  url = "/tags"
  weight = 65
  
[[zh.menu.main]]
  name = "GitHub"
  url = "https://github.com/YXL76"
  weight = 75