[[main]]
  name = "About"
  url = ""
  weight = 10

[[main]]	
  name = "Post"
  url = "/post"
  weight = 20

[[main]]	
  name = "Categories"
  url = "/categories"
  weight = 30

[[main]]	
  name = "Tags"
  url = "/tags"
  weight = 30

[[main]]
  name = "GitHub"
  url = "https://github.com/YXL76"
  weight = 70
