[[main]]	
  name = "Post"
  url = "/post"
  weight = 10
  identifier = "Post"

[[main]]	
  name = "Latest"
  url = "/post"
  weight = 20
  parent = "Post"
  
[[main]]	
  name = "Oldest"
  url = "/post"
  weight = 30
  parent = "Post"

[[main]]	
  name = "Index"
  weight = 40
  identifier = "Index"

[[main]]	
  name = "Categories"
  url = "/categories"
  weight = 50
  parent = "Index"

[[main]]	
  name = "Tags"
  url = "/tags"
  weight = 60
  parent = "Index"

[[main]]
  name = "About"
  weight = 70
  identifier = "About"
  
[[main]]
  name = "About me"
  url = ""
  weight = 80
  parent = "About"
  
[[main]]
  name = "Log"
  url = "/log"
  weight = 90
  parent = "About"

[[main]]
  name = "GitHub"
  url = "https://github.com/YXL76"
  weight = 100
