color_theme = "default"

day_night = true

font = "default"

description = ""

sharing_image = ""

twitter = ""

logo = ""

highlight = true
highlight_languages = []
highlight_style = "monokai-sublime"

math = true

privacy_pack = false

date_format = "Monday, 02 Jan 2006"
time_format = "3:04 PM"

############################
## Contact Widget setup   ##
############################

email = "chenxin.lan.76@gmail.com"

office_hours = """Monday 10:00 to 13:00<br>
                  Wednesday 09:00 to 10:00"""

appointment_url = "https://calendly.com"

contact_links = [
  {icon = "twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/Twitter"},
  {icon = "skype", icon_pack = "fab", name = "Skype Me", link = "skype:echo123?call"},
  {icon = "keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
  {icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://discourse.gohugo.io"},
  ]


############################
## Plugins                ##
############################

plugins_css = ["custom", "font"]
plugins_js  = ["custom"]

############################
## Advanced options       ##
############################

gravatar = false

menu_align_right = false

reading_time = true

comment_count = true

section_pager = false

sharing = true

[search]
  engine = 1
