[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404/"
  status = 404
  
[[redirects]]
  from = "/zh/*"
  to = "/zh/404/"
  status = 404